Create account
11michi11/Streamster pull request #1
Opened 2020-09-28 11:14 UTC by MatejMichalek

Note: Tests for RBAC not included due to problems with mocking user in Spock

2020-09-28 13:58 UTC, 11michi11 commented
Try to avoid writing lines that are longer than 120 (this line on the right in the editor) It is easier to ready it later with two editors side by side

2020-09-28 14:43 UTC, 11michi11 requested changes

2020-09-28 14:43 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/security/AuthorizationServerConfig.java
> +//                .authorities("ROLE_CLIENT", "ROLE_TRUSTED_CLIENT")
If you think that this shouldn't be there, then just delete it. Don't leave commented code

2020-09-28 14:43 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/service/UserService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,"The user cannot be found"));
Wouldn't it be better to create custom exception UserNotFoundException as this will be probably useful later? Also you can make advice for that so that it is allways mapped to correct method and message. This way we can avoid HTTP logic in the service layer

2020-09-28 15:20 UTC, MatejMichalek commented on UserService/src/main/java/com/streamster/userservice/service/UserService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,"The user cannot be found"));
ok .. I prefer solution with advices

2020-10-02 09:59 UTC, 11michi11 requested changes
Just one more change to path in updateSystemRole

2020-10-02 09:59 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/controller/UserController.java
> +    @PutMapping("/updateSystemRole/{userId}/{role}")
I'd rather use RequestParam for role. In this case user is a resource and you want to update its attribute role. And the path should be to the resource

2020-10-04 13:17 UTC, 11michi11 requested changes
Just two more things with paths

2020-10-04 13:17 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/controller/UserController.java
> +    @GetMapping("/all")
you don't need specific path to get all items from collection. So it's just @GetMapping, without the additional path

2020-10-04 13:17 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/controller/UserController.java
> +    @PutMapping("/updateSystemRole/{userId}")
I'd rather see that path like this: /users/{userId}/updateSystemRole, so that first you have path to resource

2020-10-04 13:18 UTC, 11michi11 commented on UserService/src/main/java/com/streamster/userservice/controller/UserController.java
> +    @PutMapping("/updateSystemRole/{userId}")
Also, there is merge conflict on this branch, so merge with master

2020-10-04 13:43 UTC, 11michi11 approved these changes

2020-10-04 13:43 UTC, merged